apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:          #shared! 어떤 shared 더라..db 빼고 다? => ㅇㅇ
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx      #라벨? 얘는 어떤거 말하는것 ? 이 디플로이먼트 이름 ?? => 색인
spec:
  replicas: 1
  selector:         #selector 라는게 ??
    matchLabels:
      app: nginx    #tier 은 없어도됨 ? => ㅇㅇ
  template:
    metadata:
      labels:
        app: nginx
    spec:             #얘가 파드 말하는거 맞음? => ㅇㅇ
      containers:
        - name: nginx   #저 위에 app: nginx 라벨이랑 다른거??
          image: nginx_service  #도커빌드한거 !
          imagePullPolicy: Never  #?? => github 금지한거
          ports:
            - containerPort: 80
            - containerPort: 443
